[information]
name = "night-owl"
background = "dark"
author = 'Andrés Quilodrán'

[palette]
fg = '#d6deeb'
bg = '#011627'
cursor_fg = '#80a4c2' # editorCursor.foreground
line_number_fg = '#4b6479' # editorLineNumber.foreground
line_number_active_fg = '#c5e4fc' # editorLineNumber.activeForeground
sign_add = '#9ccc65' # editorGutter.addedBackground
sign_change = '#e2b93d' # editorGutter.modifiedBackground
sign_delete = '#ef5350' # editor.errorForeground, editorGutter.deletedBackground
indent_guide = '#1f395d' # editorIndentGuide.background, editorRuler.foreground
indent_guide_active = '#7e97ac' # editorIndentGuide.activeBackground
visual = '#1d3b53' # editor.selectionBackground
match_paren = '#1D3443'
search_blue = '#073E5D'
error_red = '#ef5350' # editor.errorForeground, editorGutter.deletedBackground
word_highlight = '#2F3350'

ui_border = '#5f7e97' # list.inactiveSelectionForeGround, editorHoverWidget.border, meta.type.parameters.{ts,tsx}, entity.name.type.instance.jsdoc, statusBar.foreground
nvim_tree_file = '#89a4bb' # sideBar.foreground (text)
nvim_tree_cursor_line = '#0e293f' # list.inactiveSelectionBackground

title = '#82b1ff' # markdown punctuation
parameter = '#d7dbe0'
string_delimiter = '#d9f5dd'

dark = '#010d18'
# '#001122' - breadcrumbPicker.background
# '#010b14' - scrollbar.shadow
# '#010e1a' - titleBar.inactiveBackground
# '#01111d' - tab.inactiveBackground
# '#020e14' - invalid.broken
dark2 = '#021320'
dark3 = '#99b76d23' # use for popup_back = '#1e222a'?

white = '#ffffff'
white2 = '#eeefff'
dark_white = '#ffffffcc'

gray = '#262a39' # border
# '#1f2330' - statusBar
# '#202431' - statusBar
# '#25293a' - statusBar
# '#272b3b' - tab.border
# '#575656'
# '#4f4f4f' - textCodeBlock.background
# '#bec5d4' - variables on php and sass at-rules
# '#dddddd' - go function calls
# dark_gray = '#3e4451'
# context = '#6b737f'
# light_gray = '#c8ccd4'
# tree_gray = '#1b1f27'
gray2 = '#d2dee7' # tab.activeForeground
gray3 = '#d6deeb80' # panelTitle.inactiveForeground

light_blue = '#78ccf0' # variable.other.jsdoc
blue = '#82aaff' # function, constant, sass at-rules (?)
# '#4373c2' - selection.background
# '#00589ef2' - inputValidation.infoBackground
# '#084d8180' - scrollbarSlider
# '#0b2942'
# '#2b2f40' - editorSuggestWidget.border
# '#2c3043' - editorSuggestWidget.background
# '#2e3250' - peekViewResult.selectionBackground
# '#44596b' # activityBarBadge.background
# '#5e82ceb4' - editorCodeLens.foreground
# '#64b5f6'
# '#a2bffc' - changed (git and diff)
# '#cdebf7' - object
# '#5f7e974d' # editorBracketMatch.background
blue2 = '#0b253a' # input.background
# blue3 ='#1085bb5d' # editor.findMatchHighlightBackground
blue3 = '#122d42' # focusBorder
blue4 = '#1b90dd4d' # terminal.selectionBackground
blue5 = '#234d70' # terminalCursor.background
blue6 = '#234d708c' # list.activeSelectionBackground
blue7 = '#395a75' # gitDecoration.ignoredResourceForeground
blue8 = '#5ca7e4' # string.regexp
blue9 = '#5f7e9779' # editor.selectionHighlightBackground, editor.findMatchBackground
blue10 = '#697098' # markdown quotes
blue11 = '#8eace3' # python variable
blue12 = '#b2ccd6' # python function call

green = '#c5e478' # tag.attribute, scss variable, variables, md bold
# '#21c7a8'
# '#22da6e'
# '#8bd649'
# '#c5e47833'
# green2 = '#c5e478ff' # gitDecoration.untrackedResourceForeground
# light_green = '#c18a56'

light_cyan = '#caece6' # tag names
cyan = '#6ae9f0' # HTML punctuation definition
# '#31e1eb' - coffeescript variable assignment
# '#57eaf1'
cyan2 = '#7fdbca' # new keyword
cyan3 = '#7fdbcaff' # C++ functions
cyan4 = '#80cbc4' # strings in JSON
cyan5 = '#baebe2'
dark_cyan = '#637777'

light_red = '#ff869a'
red = '#ff5874'
# '#ef535033' - diffEditor
# '#ef53504d' - diffEditor
# '#ef5350f2'
# '#d3423e'
# '#ec5f67'
red2 = '#ff6363' # tag names in stylesheets
red3 = '#ef535090' # gitDecoration.deletedResourceForeground
dark_red = '#ab0300f2'

light_orange = '#ecc48d' # string
orange = '#f78c6c' # attribute name css, custom tag, number
orange2 = '#ffcb8b' # {js, ts} classes,

light_yellow = '#faf39f' # object.property
yellow = '#b39554' # warning color
# '#675700F2'
# '#ffca28'
# '#e0dec6'
yellow2 = '#fad430' # entity attribute id
yellow3 = '#ffeb95' # stylesheet unit keyword
yellow4 = '#ffeb95cc' # gitDecoration.conflictingResourceForeground

light_purple = '#a599e9' # breadcrumb.foreground
purple = '#7e57c2' # rulers for merge conflicts
# '#7e57c273'
# '#7e57c2cc'
# '#7e57c25a' # editor.hoverHighlightBackground
purple2 = '#7986e7' # variable.parameter.function.js
dark_purple = '#2E2D5E' # extracted directly to avoid alpha channel

magenta = '#c792ea' # keyword
# '#975f94'
# '#ff2c83'
magenta2 = '#c789d6' # json property values
magenta3 = '#d1aaff' # pickerGroup.foreground
magenta4 = '#e2a2f433' # editor.wordHighlightStrongBackground
magenta5 = '#f6bbe533' # editor.wordHighlightBackground

# alt_fg = '#8b92a8'
# alt_bg = '#1b1f27'
# accent = '#545862'
# search_orange = '#613214'
# vivid_blue = '#4FC1FF'
# dark_blue = '#223E55'
# folder_blue = '#42A5F5'

# cursor_bg = '#AEAFAD'

# tree_sign_add = '#73C991'
# tree_sign_change = '#CCA700'

# warning_orange = '#ff8800'
# info_yellow = '#FFCC66'
# hint_blue = '#4FC1FF'
# success_green = '#14C50B'

# purple_test = '#ff007c'
# cyan_test = '#00dfff'

# ui2_blue = '#042E48'
# ui3_blue = '#0195F7'
# ui4_blue = '#75BEFF'
# ui_orange = '#E8AB53'
# ui_purple = '#B180D7'

[highlights]
Normal = 'fg bg'
SignColumn = '- bg'
# MsgArea = 'fg bg'
# ModeMsg = 'fg dark'
# MsgSeparator = 'fg bg'
# SpellBad = 'light_red - u'
# SpellCap = 'yellow - u'
# SpellLocal = 'green - u'
# SpellRare = 'purple - u'
# NormalNC = 'fg bg'
Pmenu = '- dark'
PmenuSel = '- nvim_tree_cursor_line'
# WildMenu = 'fg ui2_blue'
CursorLineNr = 'line_number_active_fg'
LineNr = 'line_number_fg'
Comment = 'dark_cyan - i'
# Folded = 'accent alt_bg'
# FoldColumn = 'accent alt_bg'
FloatBorder = 'blue3 bg'
# Whitespace = 'bg -'
VertSplit = 'gray'
CursorLine = '- dark2'
CursorColumn = '- cursor_fg'
# ColorColumn = '- dark'
NormalFloat = '- bg'
Visual = 'link:VisualActive'
VisualActive = '- visual'
VisualInactive = '- dark_purple'
# VisualNOS = '- alt_bg'
# WarningMsg = 'error_red bg'
DiffAdd = 'bg sign_add'
DiffChange = 'bg sign_change u'
DiffDelete = 'bg sign_delete'
# QuickFixLine = '- ui2_blue'
# PmenuSbar = '- alt_bg'
# PmenuThumb = '- gray'
# MatchWord = '- - u'
MatchParen = '- match_paren'
# MatchWordCur = '- - u'
# MatchParenCur = '- - u'
Cursor = 'cursor_fg'
lCursor = 'cursor_fg'
CursorIM = 'cursor_fg'
TermCursor = 'cursor_fg'
TermCursorNC = 'cursor_fg'
# Conceal = 'accent'
Directory = 'blue'
# SpecialKey = 'blue - b'
Title = 'title - b'
ErrorMsg = 'link:Error'
Search = '- search_blue'
# IncSearch = 'search_orange light_gray'
# Substitute = 'light_gray search_orange'
# MoreMsg = 'orange'
# Question = 'orange'
# EndOfBuffer = 'bg'
NonText = 'bg'
# Variable = 'light_blue'
String = 'light_orange'
# Character = 'orange'
Constant = 'blue - i'
Number = 'orange'
Boolean = 'red - i'
# Float = 'light_green'
Identifier = 'light_blue'
Function = 'blue - i'
Operator = 'magenta'
Type = 'orange2' # on Neovim 0.9.0 latest dev version JS classes now inherit from this hl group
# StorageClass = 'blue'
# Structure = 'blue'
# Typedef = 'blue'
Keyword = 'magenta'
Statement = 'magenta - i'
Conditional = 'magenta'
# Repeat = 'purple'
# Label = 'purple'
# Exception = 'purple'
Include = 'magenta - i'
# PreProc = 'purple'
# Define = 'purple'
# Macro = 'purple'
# PreCondit = 'purple'
Special = 'orange2'
# SpecialChar = 'white'
Tag = 'light_cyan'
# Debug = 'red'
Delimiter = 'fg'
# SpecialComment = 'gray'
# Underlined = '- - u'
# Bold = '- - b'
# Italic = '- - i'
# Ignore = 'cyan bg b'
# Todo = 'magenta bg b'
Error = 'error_red'
# TabLine = 'light_gray line'
# TabLineSel = 'white line'
# TabLineFill = 'line line'

[Treesitter]
# TSComment = 'link:Comment'
# TSAnnotation = 'blue'
# TSAttribute = 'cyan'
# TSConstructor = 'cyan'
'@class.constructor' = 'blue - i'
'@class.field.function' = 'link:Function'
# TSType = 'cyan'
'@type' = 'orange2 - i'
'@type.class' = 'orange2 - n'
'@type.inheritedClass' = 'green - n'
'@type.toml' = 'green - i'
# TSTypeBuiltin = 'orange'
'@type.builtin' = 'green'
# TSConditional = 'yellow'
# TSException = 'purple'
# TSInclude = 'purple'
'@include.identifier' = 'fg - n'
# TSKeyword = 'purple'
'@keyword' = 'link:Keyword'
# TSKeywordReturn = 'purple'
'@keyword.return' = 'link:Statement'
'@keyword.export' = 'link:Statement'
'@keyword.default' = 'link:Statement'
'@keyword.static' = 'link:Statement'
'@keyword.extends' = 'link:Statement'
'@keyword.coroutine' = 'link:Statement'
# TSKeywordFunction = 'purple'
'@keyword.operator' = 'cyan2'
'@keyword.jsdoc' = 'magenta - n'
# TSLabel = 'light_blue'
'@label' = 'cyan2'
# TSNamespace = 'cyan'
# TSRepeat = 'yellow'
# TSConstant = 'orange'
'@constant' = 'link:Constant'
'@constant.identifier' = 'link:Constant'
# TSConstBuiltin = 'orange'
'@constant.builtin' = 'link:Constant'
'@constant.builtin.null' = 'red'
# TSFloat = 'orange'
# TSNumber = 'orange'
# TSBoolean = 'orange'
# TSCharacter = 'green'
# TSError = 'error_red'
# TSFunction = 'blue'
# TSFuncBuiltin = 'blue'
# TSMethod = 'blue'
# TSConstMacro = 'orange'
# TSFuncMacro = 'blue'
# TSVariable = 'light_blue'
'@variable' = 'link:@parameter'
# TSVariableBuiltin = 'red'
'@variable.builtin' = 'cyan2'
'@variable.object' = 'cyan2 - i'
# TSProperty = 'red'
'@property' = 'cyan5'
'@property.toml' = 'magenta - n'
'@object.property' = 'light_yellow - i'
'@object.key' = 'magenta - i'
# TSField = 'fg'
# TSParameter = 'red'
'@parameter' = 'parameter'
'@parameter.jsdoc' = 'light_blue'
# TSParameterReference = 'red'
# TSSymbol = 'light_blue'
# TSText = 'alt_fg'
'@text.literal' = 'green'
'@text.uri' = 'light_red - u'
'@text.emphasis' = 'magenta - i'
'@text.strong' = 'green - b'
'@text.todo' = 'bg fg'
# TSOperator = 'alt_fg'
'@operator.toml' = 'fg'
'@operator.of' = 'cyan2'
# TSPunctDelimiter = 'alt_fg -'
'@tag.component.jsx' = 'orange - n'
# TSTagDelimiter = 'alt_fg'
'@tag.delimiter' = 'cyan2'
# TSTagAttribute = 'orange'
'@tag.attribute' = 'green - i'
# TSPunctBracket = 'alt_fg -'
# TSPunctSpecial = 'purple'
'@punctuation.string.delimiter' = 'string_delimiter'
'@punctuation.accessor' = 'link:Statement'
# TSString = 'green'
'@string.json' = 'magenta2'
# TSStringRegex = 'green'
'@string.regex' = 'blue - n'
'@string.regexFlags' = 'blue8 - n'
# TSStringEscape = 'green'
# TSTag = 'blue'
# TSEmphasis = '- - i'
# TSUnderline = '- - u'
# TSTitle = 'fg - -'
# TSLiteral = 'orange'
# TSURI = 'orange - u'
# TSKeywordOperator = 'purple'
# TSStructure = 'light_blue'
# TSStrong = 'blue - b'
# TSQueryLinterError = 'warning_orange'
# TreesitterContext = '- tree_gray'

[markdown]
# markdownBlockquote = 'green'
# markdownCode = 'orange'
# markdownCodeBlock = 'orange'
# markdownCodeDelimiter = 'orange'
# markdownH1 = 'blue'
# markdownH2 = 'blue'
# markdownH3 = 'blue'
# markdownH4 = 'blue'
# markdownH5 = 'blue'
# markdownH6 = 'blue'
# markdownHeadingDelimiter = 'blue'
# markdownHeadingRule = 'fg - b'
# markdownId = 'purple'
# markdownIdDeclaration = 'blue'
# markdownIdDelimiter = 'light_gray'
# markdownLinkDelimiter = 'light_gray'
# markdownBold = 'blue - b'
# markdownItalic = '- - i'
# markdownBoldItalic = 'yellow - bi'
# markdownListMarker = 'blue'
# markdownOrderedListMarker = 'blue'
# markdownRule = 'accent'
# markdownUrl = 'cyan - u'
# markdownLinkText = 'blue'
# markdownFootnote = 'orange'
# markdownFootnoteDefinition = 'orange'
# markdownEscape = 'yellow'

[Whichkey]
# WhichKey = 'purple'
# WhichKeySeperator = 'green'
# WhichKeyGroup = 'blue'
# WhichKeyDesc = 'light_blue'
# WhichKeyFloat = '- dark'

[Git]
GitGutterAdd = 'sign_add -'
GitGutterChange = 'sign_change -'
GitGutterDelete = 'sign_delete -'
GitGutterChangeDelete = 'sign_change -'
# SignAdd = 'sign_add -'
# SignChange = 'sign_change -'
# SignDelete = 'sign_delete -'
# GitSignsAdd = 'sign_add -'
# GitSignsChange = 'sign_change -'
# GitSignsDelete = 'sign_delete -'

[LSP]
LspInfoBorder = "ui_border"
# LspDiagnosticsDefaultError = 'error_red'
# LspDiagnosticsDefaultWarning = 'warning_orange'
# LspDiagnosticsDefaultInformation = 'info_yellow'
# LspDiagnosticsDefaultInfo = 'info_yellow'
# LspDiagnosticsDefaultHint = 'hint_blue'
# LspDiagnosticsVirtualTextError = 'error_red'
# LspDiagnosticsVirtualTextWarning = 'warning_orange'
# LspDiagnosticsVirtualTextInformation = 'info_yellow'
# LspDiagnosticsVirtualTextInfo = 'info_yellow'
# LspDiagnosticsVirtualTextHint = 'hint_blue'
# LspDiagnosticsFloatingError = 'error_red'
# LspDiagnosticsFloatingWarning = 'warning_orange'
# LspDiagnosticsFloatingInformation = 'info_yellow'
# LspDiagnosticsFloatingInfo = 'info_yellow'
# LspDiagnosticsFloatingHint = 'hint_blue'
# DiagnosticSignError = 'error_red'
# DiagnosticSignWarning = 'warning_orange'
# DiagnosticSignInformation = 'info_yellow'
# DiagnosticSignInfo = 'info_yellow'
# DiagnosticSignHint = 'hint_blue'
# LspDiagnosticsSignError = 'error_red'
# LspDiagnosticsSignWarning = 'warning_orange'
# LspDiagnosticsSignInformation = 'info_yellow'
# LspDiagnosticsSignInfo = 'info_yellow'
# LspDiagnosticsSignHint = 'hint_blue'
# LspDiagnosticsError = 'error_red'
# LspDiagnosticsWarning = 'warning_orange'
# LspDiagnosticsInformation = 'info_yellow'
# LspDiagnosticsInfo = 'info_yellow'
# LspDiagnosticsHint = 'hint_blue'
# LspDiagnosticsUnderlineError = '- - u'
# LspDiagnosticsUnderlineWarning = '- - u'
# LspDiagnosticsUnderlineInformation = '- - u'
# LspDiagnosticsUnderlineInfo = '- - u'
# LspDiagnosticsUnderlineHint = '- - u'
# LspReferenceRead = '- #2e303b'
# LspReferenceText = '- #2e303b'
# LspReferenceWrite = '- #2e303b'
# LspCodeLens = 'context - i'
# LspCodeLensSeparator = 'context - i'
DiagnosticError = "link:Error"

[Telescope]
TelescopeSelection = '- visual'
TelescopeMatching = 'nvim_tree_file - b'
TelescopeBorder = 'ui_border'

[NvimTree]
# NvimTreeFolderIcon = 'folder_blue'
# NvimTreeIndentMarker = '#c5c5c5'
NvimTreeNormal = 'nvim_tree_file'
NvimTreeSpecialFile = 'orange'
# NvimTreeVertSplit = 'alt_bg alt_bg'
# NvimTreeFolderName = 'folder_blue'
# NvimTreeOpenedFolderName = 'folder_blue - bi'
# NvimTreeEmptyFolderName = 'gray - i'
# NvimTreeGitIgnored = 'gray - i'
NvimTreeImageFile = 'nvim_tree_file'
# NvimTreeSpecialFile = 'orange'
# NvimTreeEndOfBuffer = 'tree_gray'
# NvimTreeCursorLine = '- #282b37'
# NvimTreeGitignoreIcon = '#E64A19'
# NvimTreeGitStaged = 'tree_sign_add'
NvimTreeGitNew = 'green'
# NvimTreeGitRenamed = 'tree_sign_add'
# NvimTreeGitDeleted = 'sign_delete'
# NvimTreeGitMerge = 'tree_sign_change'
# NvimTreeGitDirty = 'tree_sign_change'
# NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'magenta'
# NvimTreeExecFile = '#9FBA89'
# NvimTreeWindowPicker = ''

[Buffer]
# BufferCurrent = 'fg bg'
# BufferCurrentIndex = 'fg bg'
# BufferCurrentMod = 'info_yellow bg'
# BufferCurrentSign = 'hint_blue bg'
# BufferCurrentTarget = 'red bg b'
# BufferVisible = 'fg bg'
# BufferVisibleIndex = 'fg bg'
# BufferVisibleMod = 'info_yellow bg'
# BufferVisibleSign = 'gray bg'
# BufferVisibleTarget = 'red bg b'
# BufferInactive = 'gray alt_bg'
# BufferInactiveIndex = 'gray alt_bg'
# BufferInactiveMod = 'info_yellow alt_bg'
# BufferInactiveSign = 'gray alt_bg'
# BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
# StatusLine = 'line gray'
# StatusLineNC = 'line gray'
# StatusLineSeparator = 'line'
# StatusLineTerm = 'line'
# StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineChar = 'indent_guide'
IndentBlanklineContextChar = 'indent_guide_active'
# IndentBlanklineContextStart = '- - u'
# IndentBlanklineSpaceChar = 'cyan_test'
# IndentBlanklineSpaceCharBlankline = 'info_yellow'

[Dashboard]
# DashboardHeader = 'blue'
# DashboardCenter = 'purple'
# DashboardFooter = 'cyan'

[Cmp]
# CmpItemAbbrDeprecated = 'gray - s'
# CmpItemAbbrMatch = 'ui3_blue'
# CmpItemAbbrMatchFuzzy = 'ui3_blue'
# CmpItemKindFunction = 'blue'
# CmpItemKindMethod = 'blue'
# CmpItemKindConstructor = 'cyan'
# CmpItemKindClass = 'cyan'
# CmpItemKindEnum = 'cyan'
# CmpItemKindEvent = 'yellow'
# CmpItemKindInterface = 'cyan'
# CmpItemKindStruct = 'cyan'
# CmpItemKindVariable = 'red'
# CmpItemKindField = 'red'
# CmpItemKindProperty = 'red'
# CmpItemKindEnumMember = 'orange'
# CmpItemKindConstant = 'orange'
# CmpItemKindKeyword = 'purple'
# CmpItemKindModule = 'cyan'
# CmpItemKindValue = 'fg'
# CmpItemKindUnit = 'fg'
# CmpItemKindText = 'fg'
# CmpItemKindSnippet = 'yellow'
# CmpItemKindFile = 'fg'
# CmpItemKindFolder = 'fg'
# CmpItemKindColor = 'fg'
# CmpItemKindReference = 'fg'
# CmpItemKindOperator = 'fg'
# CmpItemKindTypeParameter = 'red'

[Illuminate]
IlluminatedWordText = '- word_highlight'
IlluminatedWordRead = '- word_highlight'
IlluminatedWordWrite = '- word_highlight'
